### ISSUE TITLE
pddlgym_planners fails on Windows platform

### ISSUE THREAD

**Issue by MatanArgaman** [ronuchit/pddlgym_planners#10]
Hi,
I installed both pddlgym and pddl_gym_planners on a conda environment in windows, ran the example code of pddlgym_planners and got the following output and trace:

Instantiating FF
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328) - The received certificate has expired.
A subdirectory or file C:\projects\pddlgym_planners\pddlgym_planners\FF-v2.3 already exists.
tar (child): temp_ff_install.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove 'temp_ff_install.tgz': No such file or directory
'make' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\projects\pddl_play\pddl_gym_planner.py", line 6, in <module>
    ff_planner = FF()
  File "c:\projects\pddlgym_planners\pddlgym_planners\ff.py", line 24, in __init__
    self._install_ff()
  File "c:\projects\pddlgym_planners\pddlgym_planners\ff.py", line 87, in _install_ff
    assert os.path.exists(self._exec)
AssertionError

Process finished with exit code 1

**Comment by ronuchit** [comment]
Hmm, we've never tested on Windows. At the end of the day all we're doing is running [this function](https://github.com/ronuchit/pddlgym_planners/blob/master/pddlgym_planners/ff.py#L74) which has an `if` branch for Mac and an `else` branch for Linux. You'll need to modify it as needed for Windows, or simply install FF any other way. The goal of the installation is simply to reach a point where you have an executable called `FF-v2.3/ff` in the current directory. Once you have that, [this check](https://github.com/ronuchit/pddlgym_planners/blob/master/pddlgym_planners/ff.py#L23) will no longer fire, and we'll no longer call `_install_ff()`.
