### ISSUE TITLE
why this happen"sh: 1: cd: can't cd to  XXXXXX"?

### ISSUE THREAD

**Issue by Tridu33** [ronuchit/pddlgym_planners#2]
after i write ">>> ff_planner = FF()",then it show this:

```
sh: 1: cd: can't cd to /home/tridu33/rl/pddlgym_planners/FF-v2.3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tridu33/rl/pddlgym_planners/ff.py", line 24, in __init__
    self._install_ff()
  File "/home/tridu33/rl/pddlgym_planners/ff.py", line 82, in _install_ff
    assert os.path.exists(self._exec)
AssertionError
```

**Comment by Tridu33** [comment]
i am in Ubuntu 18.04.5 LTS \n \l

**Comment by Tridu33** [comment]
fine,i compile ff planner by myself and then i Comment out code

**Comment by ronuchit** [comment]
Sorry about the complications. Glad you got it working!

**Comment by emanuelazfernandes** [comment]
for anyone looking for this, I solved with `sudo apt-get install flex bison`
