### ISSUE TITLE
Issue on ubuntu 20.04

### ISSUE THREAD

**Issue by kevindokaist** [ronuchit/pddlgym_planners#4]
Hi, I am on ubuntu 20.04 with Python 3.8.5 and I tried running your test.py file. 

I get this error, on my terminal. Do you have any advice for me?

```
Traceback (most recent call last):
  File "/home/kevindo/Documents/pddlgym/test.py", line 5, in <module>
    from pddlgym_planners.ff import FF  # FastForward
  File "/home/kevindo/Documents/pddlgym/pddlgym_planners/ff.py", line 8, in <module>
    from pddlgym_planners.pddl_planner import PDDLPlanner
  File "/home/kevindo/Documents/pddlgym/pddlgym_planners/pddl_planner.py", line 14, in <module>
    from pddlgym_planners.FD.src.translate.translate import main as downward_translate
ModuleNotFoundError: No module named 'pddlgym_planners.FD'
```

Thank you!

**Comment by ronuchit** [comment]
Sorry for the inconvenience. I've just pushed a change. Let me know if that fixes it for you :)

**Comment by kevindokaist** [comment]
It seems to be fixed now. Thank you for your fast response! :)
